### ISSUE TITLE
ConcatPDF 1.3.3 のUIが日本語にならない

### ISSUE THREAD

**Issue by mkht** [kazuyaujihara/ConcatPDF#1]
GUI版ConcatPDFにおいて、
1.3.2までは日本語環境で実行した場合、メニュー表示などのUIが日本語化されていましたが、
1.3.3では常に英語表記となってしまい、日本語化されません。

現象を確認した環境は Windows 10 Pro x64 バージョン1809 日本語版 です。

#### ConcatPDF 1.3.3
![image](https://user-images.githubusercontent.com/25482642/57577591-49594300-74b5-11e9-99cb-6920ee592c7f.png)

#### ConcatPDF 1.3.2
![image](https://user-images.githubusercontent.com/25482642/57577595-70177980-74b5-11e9-82f6-e4277110c4eb.png)

ソースコードから原因究明および修正を行おうと思ったのですが、
GitHub上で公開されているソースコードは1.3.2のもので、1.3.3のソースが公開されていないようで、私の方では調査ができませんでした。

作者様のほうで修正頂くか、ご多忙であればGitHub上に最新のソースを公開していただければ私の方で修正してプルリクエストさせて頂くことも可能です。

ご検討ください。

**Comment by kazuyaujihara** [comment]
ご指摘ありがとうございます。コミットするのを忘れていたようです。原因究明してみます。

**Comment by kazuyaujihara** [comment]
.NET Framework 2.0 をターゲットにしているのですが、そのままでは多言語対応ができないようになったようです。.NET Framework 4.6.1 をターゲットにしたものを次のブランチに入れました。試してみてください。
https://github.com/kazuyaujihara/ConcatPDF/commits/net461
https://github.com/kazuyaujihara/ConcatPDF/commit/4181da86918ab1a434aecedeb406e61609bd33ac
（プレビューの機能は、PDFLibNet に依存しているためこのままでは動きません）

**Comment by mkht** [comment]
対応ありがとうございます。
手元のVisual Studio 2017でビルドし、UIが日本語で表示されることを確認しました。

**Comment by k-ujihara** [comment]
This issue has been fixed in  [v1.4.0](https://github.com/kazuyaujihara/ConcatPDF/tree/v1.4.0).
